/**
 * Error tracking and observability endpoints.
 */

import { Router, Request, Response } from 'express';
import { captureException, getApmSummary, getRecentApmSamples } from '../lib/observability';

const router = Router();

router.get('/monitoring/status', (_req: Request, res: Response) => {
  return res.status(200).json({
    success: true,
    monitoring: {
      sentryEnabled: Boolean(process.env.SENTRY_DSN),
      apm: getApmSummary(),
    },
  });
});

router.get('/monitoring/apm', (_req: Request, res: Response) => {
  return res.status(200).json({
    success: true,
    samples: getRecentApmSamples(20),
    summary: getApmSummary(),
  });
});

router.post('/monitoring/test-error', (req: Request, res: Response) => {
  const source = req.body?.source || 'manual';
  const error = new Error(`Test error generated by ${source}`);
  captureException(error, { source, endpoint: '/monitoring/test-error' });

  return res.status(200).json({
    success: true,
    message: 'Synthetic error reported to observability pipeline',
  });
});

export default router;
