import { Link } from "wouter";
import { ArrowRight, BarChart3, Check, ChevronRight, CircleDollarSign, LockKeyhole, ShieldCheck, Sparkles, WalletCards, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useLiveMarkets, formatPrice } from "@/lib/market-data";

export function PublicHome() {
  const markets = useLiveMarkets();
  const featured = markets.slice(0, 5);

  return <div className="public-home">
    <div className="public-ticker"><div className="public-container flex min-w-max gap-8 py-3">{[...featured, ...featured].map((market, index) => <div key={`${market.symbol}-${index}`} className="flex items-center gap-3 text-xs"><span className="font-semibold text-white/75">{market.symbol}</span><span className="font-mono text-white/55">{formatPrice(market.bid)}</span><span className={market.changePct >= 0 ? "public-positive" : "public-negative"}>{market.changePct >= 0 ? "+" : ""}{market.changePct.toFixed(2)}%</span></div>)}</div></div>
    <section className="public-hero"><div className="public-grid-lines" /><div className="public-container relative grid items-center gap-14 py-20 md:py-28 lg:grid-cols-[1.05fr_0.95fr]"><div className="public-reveal"><p className="public-kicker"><span className="public-live-dot" /> Markets open your way</p><h1>Every market.<br /><span>One account.</span><br />Total clarity.</h1><p className="public-lead">Trade forex, crypto, stocks, indices and commodities through one focused platform built for better decisions.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild className="public-button public-button-solid public-button-large" data-testid="button-hero-signup"><Link href="/signup">Open an account <ArrowRight /></Link></Button><Button asChild variant="outline" className="public-button public-button-outline public-button-large" data-testid="button-hero-markets"><Link href="/markets">Explore markets</Link></Button></div><div className="mt-10 flex flex-wrap gap-x-8 gap-y-3 text-xs text-white/45"><span className="inline-flex items-center gap-2"><Check className="h-4 w-4 text-primary" /> No platform fee</span><span className="inline-flex items-center gap-2"><Check className="h-4 w-4 text-primary" /> Demo access available</span><span className="inline-flex items-center gap-2"><Check className="h-4 w-4 text-primary" /> Built for clarity</span></div></div><div className="public-market-panel public-reveal public-reveal-delay"><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div><p className="text-xs uppercase tracking-[0.18em] text-white/40">Market overview</p><p className="mt-1 text-sm font-semibold">Today&apos;s movement</p></div><span className="public-status">Live</span></div><div className="p-3">{featured.map((market, index) => <div key={market.symbol} className="public-market-row"><div className="flex items-center gap-3"><span className="public-market-index">0{index + 1}</span><div><p className="text-sm font-semibold text-white">{market.symbol}</p><p className="text-xs text-white/35">{market.name}</p></div></div><div className="text-right"><p className="font-mono text-sm text-white">{formatPrice(market.bid)}</p><p className={market.changePct >= 0 ? "public-positive text-xs" : "public-negative text-xs"}>{market.changePct >= 0 ? "+" : ""}{market.changePct.toFixed(2)}%</p></div></div>)}</div><Link href="/markets" className="flex items-center justify-between border-t border-white/10 px-5 py-4 text-xs font-semibold text-primary">View all markets <ChevronRight className="h-4 w-4" /></Link></div></div></section>
    <section className="public-section public-section-border"><div className="public-container grid gap-10 md:grid-cols-3"><Metric value="24/7" label="Access to global markets" /><Metric value="5" label="Asset classes, one account" /><Metric value="1" label="Clear place to start" /></div></section>
    <section className="public-section"><div className="public-container"><div className="public-section-heading"><div><p className="public-kicker">A better starting point</p><h2>Clarity at every step.</h2></div><p>From first trade to active portfolio, the experience stays focused on the information that matters.</p></div><div className="grid gap-4 md:grid-cols-3"><Feature icon={Sparkles} number="01" title="See the bigger picture" text="Understand markets with clean watchlists, useful context and live price movement." /><Feature icon={Zap} number="02" title="Move with purpose" text="Make trades with streamlined tools designed to keep the important details visible." /><Feature icon={ShieldCheck} number="03" title="Stay in control" text="Set your direction with transparent account views and practical risk awareness." /></div></div></section>
    <section className="public-section public-section-muted"><div className="public-container grid items-center gap-12 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="public-kicker">One view, many possibilities</p><h2>Built around the way markets actually move.</h2><p className="public-copy">Follow currency pairs, digital assets, major indices, commodities and leading companies without losing the thread.</p><Button asChild variant="outline" className="public-button public-button-outline mt-7"><Link href="/markets">Browse markets <ArrowRight /></Link></Button></div><div className="grid gap-3 sm:grid-cols-2"><Asset icon={BarChart3} title="Forex" text="Major and minor currency pairs" /><Asset icon={CircleDollarSign} title="Crypto" text="Digital assets and evolving markets" /><Asset icon={WalletCards} title="Stocks" text="Companies shaping the world" /><Asset icon={LockKeyhole} title="Commodities" text="Energy, metals and more" /></div></div></section>
    <section className="public-section"><div className="public-container public-cta"><div><p className="public-kicker">Start with your next decision</p><h2>Make room for a clearer way forward.</h2></div><Button asChild className="public-button public-button-solid public-button-large"><Link href="/signup">Get started <ArrowRight /></Link></Button></div></section>
  </div>;
}

function Metric({ value, label }: { value: string; label: string }) { return <div><p className="public-metric">{value}</p><p className="text-sm text-white/45">{label}</p></div>; }
function Feature({ icon: Icon, number, title, text }: { icon: typeof Sparkles; number: string; title: string; text: string }) { return <article className="public-feature"><div className="flex items-center justify-between"><Icon className="h-5 w-5 text-primary" /><span className="font-mono text-xs text-white/25">{number}</span></div><h3>{title}</h3><p>{text}</p></article>; }
function Asset({ icon: Icon, title, text }: { icon: typeof BarChart3; title: string; text: string }) { return <Link href="/markets" className="public-asset"><Icon className="h-5 w-5 text-primary" /><div><h3>{title}</h3><p>{text}</p></div><ArrowRight className="ml-auto h-4 w-4 text-white/25" /></Link>; }
